import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs/promises";
import { watch } from "fs";
import { fileURLToPath } from "url";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// This script lives at packages/obsidian-bible-reference/scripts/.
// The plugin source is in ../src; the shippable artifacts (main.js, manifest.json,
// versions.json, styles.css) live at the repo root so the repo root doubles as the
// installable Obsidian plugin folder.
const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptsDir, "..");
const repoRoot = path.resolve(packageDir, "..", "..");

const prod = (process.argv[2] === "production");
// Default output is the repo root. Override with OUT_DIR or the third CLI arg
// (e.g. a vault's plugin folder) for local hot-dev.
const outDir = process.env.OUT_DIR || process.argv[3] || repoRoot;
const resolvedOutDir = path.resolve(outDir);

const staticFiles = [
	'styles.css',
	'manifest.json',
	'versions.json',
];

async function copyStaticFiles() {
	// When building to the repo root the static files already live there.
	if (resolvedOutDir === repoRoot) {
		return;
	}
	try {
		await fs.mkdir(resolvedOutDir, { recursive: true });
		for (const f of staticFiles) {
			const src = path.join(repoRoot, f);
			const dest = path.join(resolvedOutDir, path.basename(f));
			try {
				await fs.copyFile(src, dest);
				console.log(`copied ${src} -> ${dest}`);
			} catch (err) {
				console.warn(`warning: failed to copy ${src} -> ${dest}:`, err.message);
			}
		}
	} catch (err) {
		console.error('error ensuring out dir or copying files:', err);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [path.join(packageDir, 'src/main.ts')],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: resolvedOutDir,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Copy static files for production build
	await copyStaticFiles();
	console.log('Built to', resolvedOutDir);
	process.exit(0);
} else {
	await context.watch();
	// Initial copy for dev/watch so OUT_DIR has static assets immediately
	await copyStaticFiles();
	console.log('Watching — output ->', resolvedOutDir);

	// Watch the static files and copy on change so dev:out stays up-to-date
	for (const f of staticFiles) {
		try {
			watch(path.join(repoRoot, f), { persistent: false }, (eventType) => {
				if (eventType === 'change' || eventType === 'rename') {
					copyStaticFiles().catch(err => console.error('error copying static files:', err));
				}
			});
		} catch (err) {
			console.warn(`warning: could not watch ${f}:`, err.message);
		}
	}
}
